spring:
  application:
    name: schoolsystem
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?useSSL=false
    username: postgres
    password: "Ashish12345687"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true